name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     # -  name: Set up QEMU
      #-  uses: docker/setup-qemu-action@v2
      
      #-  name: Set up Docker Buildx
      #-  uses: docker/setup-buildx-action@v2
      
      -  uses: actions/checkout@v2
      -  name: Login to Docker Hub
         env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            
         run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
     # - name: Build Image
      #  run: docker build . --file Dockerfile --tag douglasvenes/desafio
        
      #- name: Docker push
       # run: docker push ${{secrets.DOCKERHUB_USERNAME}}/douglas-venes
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/douglas-venes:latest
      
      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f deployment.yaml
